baseURL = 'https://an-re-io.github.io/alt-soc-site/'
title = 'AltSoc'
theme = "hugo-bearcub"
defaultContentLanguage = 'ru'
canonifyURLs = true

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menus.main]]
    name = 'Infrastructure'
    url = '/infrastructure/'
    weight = 20
  [[menus.main]]
    name = 'Our Values'
    url = '/values/'
    weight = 30
    

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1

  [languages.ru]
    contentDir = 'content/ru'
    languageCode = 'ru-RU'
    languageName = 'Russian'
    weight = 2
    
